version: '3'

services:
  aspire-opentelemetrydemo:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      - OTEL_TRACES_ENDPOINT=http://otel-collector:4317
      - OTEL_LOGS_ENDPOINT=http://otel-collector:4317
      - OTEL_METRICS_ENDPOINT=http://otel-collector:4317
    networks:
      - aspire-net
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.118.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/aspire/collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - aspire-net
    depends_on:
      - aspire

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.1.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS="true"
    ports:
      - "18888:18888"
    networks:
      - aspire-net

volumes:
  aspire-data:

networks:
  aspire-net:
    driver: bridge