receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/loki:
    endpoint: "http://lgtm-loki:3100/otlp"
  otlphttp/mimir:
    endpoint: "http://lgtm-mimir:9090/otlp"
  otlp/traces:
    endpoint: "lgtm-tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/mimir]
    traces:
      receivers: [otlp]
      exporters: [otlp/traces]