server:
  http_listen_port: 3200
  log_level: debug

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "lgtm-tempo:4317"
        http:
          endpoint: "lgtm-tempo:4318"

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks