version: 2
traces-pipeline:
  source:
    otel_trace_source:
      ssl: false
      port: 21890
  sink:
    - stdout:
    - pipeline:
        name: "traces-raw-pipeline"
    - pipeline:
        name: "traces-service-map-pipeline"

traces-raw-pipeline:
  source:
    pipeline:
      name: "traces-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: trace-analytics-raw

traces-service-map-pipeline:
  delay: "100"
  source:
    pipeline:
      name: "traces-pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: trace-analytics-service-map

logs-pipeline:
  source:
    otel_logs_source:
      ssl: false
      port: 21891
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: custom
        index: ss4o_logs-%{yyyy.MM.dd}        

metrics-pipeline:
  source:
    otel_metrics_source:
      ssl: false
      port: 21892
  processor:
    - otel_metrics:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: custom
        index: ss4o_metrics-otel-%{yyyy.MM.dd}        
        template_type: "index-template"
        # Workaround for https://github.com/opensearch-project/dashboards-observability/issues/2172
        # Currently only histograms are working https://github.com/opensearch-project/dashboards-observability/issues/2236
        template_content: |
          {
            "index_patterns": [
              "ss4o_metrics-*-*"
            ],
            "template": {
              "mappings": {
                "_meta": {
                  "version": "1.0.0",
                  "catalog": "observability",
                  "type": "metrics",
                  "component": "metrics",
                  "correlations" : [
                    {
                      "field": "spanId",
                      "foreign-schema" : "traces",
                      "foreign-field" : "spanId"
                    },
                    {
                      "field": "traceId",
                      "foreign-schema" : "traces",
                      "foreign-field" : "traceId"
                    }
                  ]
                },
                "_source": {
                  "enabled": true
                },
                "dynamic_templates": [
                  {
                    "exemplar_attributes_map": {
                      "mapping": {
                        "type": "keyword"
                      },
                      "path_match": "exemplar.attributes.*"
                    }
                  },
                  {
                    "instrumentation_scope_attributes_map": {
                      "mapping": {
                        "type": "keyword"
                      },
                      "path_match": "instrumentationScope.attributes.*"
                    }
                  }
                ],
                "properties": {
                  "serviceName": {
                    "type": "keyword"
                  },
                  "name": {
                    "type": "keyword",
                    "ignore_above": 256
                  },
                  "attributes": {
                    "type": "object",
                    "properties": {
                      "data_stream": {
                        "properties": {
                          "dataset": {
                            "ignore_above": 128,
                            "type": "keyword"
                          },
                          "namespace": {
                            "ignore_above": 128,
                            "type": "keyword"
                          },
                          "type": {
                            "ignore_above": 56,
                            "type": "keyword"
                          }
                        }
                      }
                    }
                  },
                  "description": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  },
                  "unit": {
                    "type": "keyword",
                    "ignore_above": 128
                  },
                  "kind": {
                    "type": "keyword",
                    "ignore_above": 128
                  },
                  "aggregationTemporality": {
                    "type": "keyword",
                    "ignore_above": 128
                  },
                  "monotonic": {
                    "type": "boolean"
                  },
                  "startTime": {
                    "type": "date"
                  },
                  "@timestamp": {
                    "type": "date"
                  },
                  "observedTimestamp": {
                    "type": "date_nanos"
                  },
                  "value@int": {
                    "type": "integer"
                  },
                  "value@double": {
                    "type": "double"
                  },
                  "buckets": {
                    "type" : "nested",
                    "properties": {
                      "count": {
                        "type": "long"
                      },
                      "sum": {
                        "type": "double"
                      },
                      "max": {
                        "type": "float"
                      },
                      "min": {
                        "type": "float"
                      }
                    }
                  },
                  "bucketCount": {
                    "type": "long"
                  },
                  "bucketCountsList": {
                    "type": "long"
                  },
                  "explicitBoundsList": {
                    "type": "float"
                  },
                  "explicitBoundsCount": {
                    "type": "float"
                  },
                  "quantiles": {
                    "properties": {
                      "quantile": {
                        "type": "double"
                      },
                      "value": {
                        "type": "double"
                      }
                    }
                  },
                  "quantileValuesCount": {
                    "type": "long"
                  },
                  "positiveBuckets": {
                    "type" : "nested",
                    "properties": {
                      "count": {
                        "type": "long"
                      },
                      "max": {
                        "type": "float"
                      },
                      "min": {
                        "type": "float"
                      }
                    }
                  },
                  "negativeBuckets": {
                    "type" : "nested",
                    "properties": {
                      "count": {
                        "type": "long"
                      },
                      "max": {
                        "type": "float"
                      },
                      "min": {
                        "type": "float"
                      }
                    }
                  },
                  "negativeOffset": {
                    "type": "integer"
                  },
                  "positiveOffset": {
                    "type": "integer"
                  },
                  "zeroCount": {
                    "type": "long"
                  },
                  "scale": {
                    "type": "long"
                  },
                  "max": {
                    "type": "float"
                  },
                  "min": {
                    "type": "float"
                  },
                  "sum": {
                    "type": "float"
                  },
                  "count": {
                    "type": "long"
                  },
                  "exemplar": {
                    "properties": {
                      "time": {
                        "type": "date"
                      },
                      "traceId": {
                        "ignore_above": 256,
                        "type": "keyword"
                      },
                      "serviceName": {
                        "ignore_above": 256,
                        "type": "keyword"
                      },
                      "spanId": {
                        "ignore_above": 256,
                        "type": "keyword"
                      }
                    }
                  },
                  "instrumentationScope": {
                    "properties": {
                      "name": {
                        "type": "keyword",
                        "ignore_above": 256
                      },
                      "version": {
                        "type": "keyword",
                        "ignore_above": 256
                      },
                      "droppedAttributesCount": {
                        "type": "integer"
                      },
                      "schemaUrl": {
                        "type": "text",
                        "fields": {
                          "keyword": {
                            "type": "keyword",
                            "ignore_above": 256
                          }
                        }
                      }
                    }
                  },
                  "schemaUrl": {
                    "type": "text",
                    "fields": {
                      "keyword": {
                        "type": "keyword",
                        "ignore_above": 256
                      }
                    }
                  }
                }
              },
              "aliases" : {
                "otel-metrics-" : {}
              },
              "settings": {
                "index": {
                  "mapping": {
                    "total_fields": {
                      "limit": 10000
                    }
                  },
                  "refresh_interval": "5s"
                }
              }
            },
            "composed_of": [],
            "version": 1,
            "_meta": {
              "description": "Observability Metrics Mapping Template",
              "catalog": "observability",
              "type": "metrics",
              "correlations" : [
                {
                  "field": "spanId",
                  "foreign-schema" : "traces",
                  "foreign-field" : "spanId"
                },
                {
                  "field": "traceId",
                  "foreign-schema" : "traces",
                  "foreign-field" : "traceId"
                }
              ]
            }
          }